version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: school_mgmt_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school_mgmt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - school_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: school_mgmt_backend
    ports:
      - "5007:5007"
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/school_mgmt
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - school_network

  go-service:
    build:
      context: ./go-service
      dockerfile: Dockerfile
    container_name: school_mgmt_pdf_service
    ports:
      - "8080:8080"
    env_file:
      - ./go-service/.env
    environment:
      - BACKEND_URL=http://backend:5007
    depends_on:
      - backend
    networks:
      - school_network

volumes:
  postgres_data:
    driver: local

networks:
  school_network:
    driver: bridge
