openapi: 3.0.3
info:
  title: Student Report Service
  description: Service for generating student PDF reports
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development

paths:
  /health:
    get:
      summary: Health check endpoint
      operationId: healthCheck
      responses:
        '200':
          description: Service health status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [healthy, degraded]
                  service:
                    type: string
                  backend:
                    type: object
                    properties:
                      reachable:
                        type: boolean

  /api/v1/students/{studentId}/report:
    get:
      summary: Generate student report PDF
      operationId: getStudentReport
      parameters:
        - name: studentId
          in: path
          required: true
          description: Student ID
          schema:
            type: string
            pattern: '^[0-9]+$'
      responses:
        '200':
          description: PDF report generated successfully
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid student ID format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Student not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '503':
          description: Backend service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        request_id:
          type: string
