openapi: 3.0.3
info:
  title: Student Report Service
  description: Service for generating student PDF reports
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development

paths:
  /health:
    get:
      summary: Health check endpoint
      operationId: healthCheck
      responses:
        '200':
          description: Service health status
          headers:
            X-Request-ID:
              description: Unique request identifier
              schema:
                type: string
                format: uuid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /api/v1/students/{studentId}/report:
    get:
      summary: Generate student report PDF
      operationId: getStudentReport
      parameters:
        - name: studentId
          in: path
          required: true
          description: Student ID (1-20 digits)
          schema:
            type: string
            pattern: '^[0-9]{1,20}$'
      responses:
        '200':
          description: PDF report generated successfully
          headers:
            Content-Disposition:
              description: Attachment filename for the PDF
              schema:
                type: string
                example: 'attachment; filename=student_123_report.pdf'
            X-Request-ID:
              description: Unique request identifier
              schema:
                type: string
                format: uuid
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid student ID format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Student not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error (PDF generation failed)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '503':
          description: Backend service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
          example: "Student not found"
      example:
        error: "Student ID must be numeric (1-20 digits)"

    HealthResponse:
      type: object
      required:
        - status
        - service
        - backend
      properties:
        status:
          type: string
          enum: [healthy, degraded]
          description: Overall service health status
        service:
          type: string
          description: Service name
          example: "go-report-service"
        backend:
          type: object
          properties:
            reachable:
              type: boolean
              description: Whether the backend service is reachable
      example:
        status: "healthy"
        service: "go-report-service"
        backend:
          reachable: true
